
spring:
  application:
    name: learn-graphql-java

server:
  http2:
    enabled: true
graphql:
  tools:
    schema-location-pattern: '**/*.graphqls'
  servlet:
    max-query-depth: 3
    exception-handlers-enabled: false
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    enabled: true # Disable for prod environments
