
spring:
  application:
    name: learn-graphql-java
  servlet:
    multipart:
      max-file-size: '1MB'

server:
  http2:
    enabled: true
graphql:
  tools:
    schema-location-pattern: '**/*.graphqls'

  servlet:
    max-query-depth: 10
    exception-handlers-enabled: false
    tracing-enabled: true
  playground:
    headers:
      Authorization: Bearer TOKEN
      user_id: John Doe
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    enabled: true # Disable for prod environments

logging:
  pattern:
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx

